
note: 'train'
# configs of data

model: 'deeplab'
train: True
multigpu: False
fixbn: True
fix_seed: True


# target Plabel
cb_prop: 0.1
num_center: 10
lamb: 0.5 

# source Image Selection
src_count: 1191
src_pix_prop: 0.9
src_pix_select: True
pool_prop: 0.2

# Selction and Fix 
src_fix: False
tgt_fix: False
src_select: True
tgt_select: True

# Re start training
resume: False
start: 0
round_start: 0

# Optimizaers
learning_rate: 7.5e-5
num_steps: 5000
epochs: 2
weight_decay: 0.0005
momentum: 0.9
power: 0.9
round: 6

# Logging
print_freq: 10
save_freq: 2000
tensorboard: False
neptune: False
screen: True
val: True
val_freq: 150

# Dataset 
source: 'cityscapes' 
target: 'darkzurich'
target_val: 'darkzurich_val' 
worker: 4
batch_size: 4 #chg
num_classes: 19

#Transforms
input_src: 720
input_tgt: 720
crop_src: 600
crop_tgt: 600
mirror: True
scale_min: 0.5
scale_max: 1.5
rec: False
        
# Model hypers
init_weight: '../scratch/saved_models/CCM/source/model410_city_deeplabv2.pth'
# init_weight: '../scratch/saved_models/CCM/source/gta5_source_only.pth' # fake cityscapes prediction
restore_from: None

snapshot: '../scratch/saved_models/CCM/save/'
result: '../scratch/saved_models/CCM/miou_result/'
log: '../scratch/saved_models/CCM/log/'
plabel: '../scratch/saved_models/CCM/plabel/'
gta5: {
        data_dir: '/data/uts200/guangrui/gta5/',
        data_list: './dataset/list/gta5_list.txt',
        input_size: [1280, 720]
        }
synthia: {
        data_dir: '/home/guangrui/data/synthia/',
        data_list: './dataset/list/synthia_list.txt',
        input_size: [1280, 760]
        }
cityscapes: {
        data_dir: '../scratch/data/cityscapes/',
        data_list: './dataset/list/cityscapes/train.txt',
        input_size: [1024, 512]
        }
cityscapes_val: {
        data_dir: '../scratch/data/cityscapes/',
        data_list: './dataset/list/cityscapes/val.txt',
        input_size: [1024, 512]
        }
darkzurich: {
        data_dir: "../scratch/data/dark_zurich/",
        data_list: './dataset/list/darkzurich/train.txt',
        input_size: [1024,512]
}
darkzurich_val: {
        data_dir: "../scratch/data/dark_zurich_val/",
        data_list: './dataset/list/darkzurich/val.txt',
        input_size: [1024,512]
}
